// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUWtyt09K8X4K_mroPZNiATxzihGLUm7I',
    appId: '1:718978849093:web:2e4b42831bf2d7aa59862c',
    messagingSenderId: '718978849093',
    projectId: 'studio-3622405336-5e2ba',
    authDomain: 'studio-3622405336-5e2ba.firebaseapp.com',
    storageBucket: 'studio-3622405336-5e2ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3HJgHGI87bfNlYjeHnwklQD5rFDgn5fU',
    appId: '1:718978849093:android:09c4011a6953529f59862c',
    messagingSenderId: '718978849093',
    projectId: 'studio-3622405336-5e2ba',
    storageBucket: 'studio-3622405336-5e2ba.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUWtyt09K8X4K_mroPZNiATxzihGLUm7I',
    appId: '1:718978849093:web:2e4b42831bf2d7aa59862c',
    messagingSenderId: '718978849093',
    projectId: 'studio-3622405336-5e2ba',
    authDomain: 'studio-3622405336-5e2ba.firebaseapp.com',
    storageBucket: 'studio-3622405336-5e2ba.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW6VWRhr0yHg2p-W7XW7MOMZFv2k2fmSA',
    appId: '1:718978849093:ios:2a7aea2ea75bc55e59862c',
    messagingSenderId: '718978849093',
    projectId: 'studio-3622405336-5e2ba',
    storageBucket: 'studio-3622405336-5e2ba.firebasestorage.app',
    iosBundleId: 'com.rathenesh.wakeupdarling',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW6VWRhr0yHg2p-W7XW7MOMZFv2k2fmSA',
    appId: '1:718978849093:ios:2a7aea2ea75bc55e59862c',
    messagingSenderId: '718978849093',
    projectId: 'studio-3622405336-5e2ba',
    storageBucket: 'studio-3622405336-5e2ba.firebasestorage.app',
    iosBundleId: 'com.rathenesh.wakeupdarling',
  );

}